Adding Swagger docs for Teams
bluehalo/node-rest-starter pull request #144
Opened 2021-10-08 20:17 UTC by brianghig

Also adding apiDocs to config controller to enable the API Docs link on the UI.

2021-10-11 17:26 UTC, jrassa commented on src/app/core/teams/teams.service.js
> +	return readTeam(savedTeam._id);
Do we need to query for the team here?  Couldn't we just return `savedTeam`?

2021-10-12 12:30 UTC, brianghig commented on src/app/core/teams/teams.service.js
> +	return readTeam(savedTeam._id);
We could, but I wanted to ensure a consistent and maintainable response from the return of a single team. By relying on the `readTeam` method, I figured it would apply any enrichments, hydrations, etc. across the board. Is there a better way to do that?

In this particular case, the `savedTeam` object stores the full `User` object in the `creator` field, instead of simply the unique user ID. So, the response is:

```
{
  ...
  creator: {
    id: "abc123def456...",
    roles: { ... },
    teams: [ { ... } ],
    name: "Full Name",
    ....
  },
  creatorName: "Full Name",
  ...
}
```

2021-10-13 17:28 UTC, tnguyenasym commented
@brianghig I finished adding documentation to the rest of the routes that were WIP, so this should be ready for final review now.

2021-10-13 17:30 UTC, tnguyenasym approved these changes
Looks good to me

2021-10-14 14:03 UTC, jrassa requested changes

2021-10-14 14:03 UTC, jrassa commented on src/app/core/teams/teams.routes.js
> + */
Missing `requestBody` definition

2021-10-14 14:03 UTC, jrassa commented on src/app/core/teams/teams.routes.js
> + *         description: Update unsuccessful. Could not find team.
Missing `requestBody` definition

2021-10-14 14:03 UTC, jrassa commented on src/app/core/teams/teams.routes.js
> + *         description: Request for team access unsuccessful. Could not find team.
Missing `requestBody` definition

2021-10-14 14:03 UTC, jrassa commented on src/app/core/teams/teams.routes.js
> + *         $ref: '#/components/responses/RequestNewTeam'
Missing `requestBody` definition

2021-10-14 16:11 UTC, tnguyenasym commented
@jrassa Thanks for the catches, added missing request body definitions

2021-10-15 01:46 UTC, brianghig commented
@jrassa @tnguyenasym - I made a few more updates to the Teams Service and its querying of users. In particular, I found that the `./team/{teamId}/members` search service was returning all of the properties of each user, including the encrypted password, salt, etc.

By switching over to the `User.filteredCopy(...)` method, we use a consistent mechanism to return publicly available and appropriate information for each user.

Any objections or concerns with this change?

2021-10-15 15:20 UTC, tzfx commented on src/app/core/teams/team.model.js
> +	const toReturn = dbs.admin.model('User').filteredCopy(user);
😏

2021-10-15 15:42 UTC, tzfx requested changes

2021-10-15 15:42 UTC, tzfx commented on src/app/core/teams/team.model.js
> +	const toReturn = dbs.admin.model('User').filteredCopy(user);
@brianghig Would you mind adding some test coverage for this? It looks like `team.model.spec.js` actually setup an expectation for the user block to contain the sensitive information, but the actual test cases never checks the userobject deeply enough for us to have caught this. `team.controller.spec.js` similarly provides a `toObject` stub for the user though appears to just do simple error checking. 

I think just a test that teamcopy  defers to user.filteredCopy and shoves the teams on there would be sufficient. 
And it looks like we probably want a test that user.filteredCopy does what we think it does.. There doesn't appear to be any direct test coverage on that in `user.model.spec.js`.

2021-10-19 16:36 UTC, tzfx commented on src/app/core/teams/team.model.js
> +	const toReturn = dbs.admin.model('User').filteredCopy(user);
Updated test cases.

2021-10-19 16:36 UTC, tzfx approved these changes

2021-10-19 18:04 UTC, jrassa approved these changes

2021-10-19 18:05 UTC, merged